jwt:
  secret: secret
  duration: 86400000 #ms in a day

server:
  port: 8090

spring:
  datasource:
    url: jdbc:h2:mem:db
    platform: h2
  h2:
    console:
      enabled: true
      path: /h2-console
